a=int (input("Enter a Value for A:"))
b=int (input("Enter a Value for B:"))
print ("A = ",a," and B = ",b)
print ("The a==b = ",a==b)
print ("The a < b = ",a>b)
print ("The a >= b = ",a>=b)
print ("The a <= b = ",a<=b)
print ("The b >= a =",b>=a)
print("The sum =",a+b)